name: NNA Registry Service CI/CD (prod)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: gcr.io/${{ secrets.GCP_PROJECT_ID }}/nna-registry-service-prod:${{ github.sha }}-${{ github.run_id }}-prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build Docker image
        run: docker build --platform linux/amd64 --no-cache -t $IMAGE_TAG .

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker for Google Cloud
        run: gcloud auth configure-docker

      - name: Push Docker image
        run: docker push $IMAGE_TAG

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy nna-registry-service-prod \
            --image $IMAGE_TAG \
            --region us-central1 \
            --platform managed \
            --service-account=nna-registry-service-prod@revize-453014.iam.gserviceaccount.com \
            --allow-unauthenticated \
            --set-secrets="MONGODB_URI=mongodb-uri-prod:latest,JWT_SECRET=JWT_SECRET_PROD:latest,GCP_BUCKET_NAME=GCP_BUCKET_NAME_PROD:latest,SENTRY_DSN=sentry-dsn:latest,/etc/gcp/key=gcp-sa-key-prod:latest" \
            --set-env-vars "NODE_ENV=production,ENVIRONMENT=production,GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }},GOOGLE_APPLICATION_CREDENTIALS=/etc/gcp/key"

# Forcing a new build after removing .dockerignore
# Triggering a new build after rollback.
